version: "3"
services:

  #PHP Service
  fpm:
    build:
      context: .
      dockerfile: resources/ops/docker/fpm/Dockerfile
    image: dorkden/ecom-api-v3-fpm
    container_name: fpm
    restart: unless-stopped
    tty: true
    environment:
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www/html/
    networks:
      - app-network
    volumes:
      - ./:/var/www/html/

  db:
    image: postgres:10.21-alpine
    restart: unless-stopped
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - 5432:5432

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./resources/ops/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
