apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-api-v3-configmap
data:
  APP_KEY: base64:RuoTFdOBuX40Xz4XxZ7RHamVwJFejgpDsX6TAWIF1qg=

  APP_NAME: ecom-api-v3
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: http://localhost:8080

  LOG_CHANNEL: stdout
  LOG_LEVEL: debug

  BROADCAST_DRIVER: log

  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync

  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"

  MAIL_MAILER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: 972f006c1cc75c
  MAIL_PASSWORD: 6c727555190e21
  MAIL_ENCRYPTION: tls

  PROMETHEUS_NAMESPACE: default
  PROMETHEUS_METRICS_ROUTE_ENABLED: "true"
  PROMETHEUS_METRICS_ROUTE_PATH: metrics
  PROMETHEUS_METRICS_ROUTE_MIDDLEWARE: "null"
  PROMETHEUS_STORAGE_ADAPTER: memory

  REDIS_HOST: redis-master
  REDIS_PORT: "6379"
  PROMETHEUS_REDIS_PREFIX: PROMETHEUS_

  
